### ISSUE TITLE
Talisman of Perseverance

### ISSUE THREAD

**Issue by arslancharyev31** [Razzmatazzz/RemnantSaveManager#11]
Talisman of Perseverance appears in both Normal and Survival categories under the Missing Items tab. Not a big deal, but it could be a source of confusion for some people.

P.S. Great app

**Comment by Razzmatazzz** [comment]
Working as intended. [It's also a random drop in Yaesha](https://www.reddit.com/r/remnantgame/comments/gecq6g/i_unlocked_the_talisman_of_perseverance_in_the/fpmpoea/). Glad you've found the app useful!
