### ISSUE TITLE
Feature Request: List characters that don't have a class

### ISSUE THREAD

**Issue by JTF195** [Razzmatazzz/RemnantSaveManager#12]
Currently, if a character hasn't picked a class, it won't show them in the Progression column

With a little bit of gamesave manipulation, it's actually possible to get a character out of the tutorial without picking a class.

Would it be possible to add those characters to the list? (as "Classless" maybe)

**Comment by JTF195** [comment]
For testing purposes, here's how you do it:
Create a new character and play through the tutorial until you have the D.A.T.L.A. Key.
Back up the save_X.sav file corresponding to that character
Create a fresh character.
Copy the save_X.sav file from the previous character, and complete the tutorial.

This will result in a character that has completed the tutorial without losing the Sword of Adventure, picking a class, or being forced to upgrade any items to +1

**Comment by Razzmatazzz** [comment]
New version should now detect characters who haven't chosen an archetype.
