### ISSUE TITLE
World isn't being analyzed

### ISSUE THREAD

**Issue by Toonsie** [Razzmatazzz/RemnantSaveManager#14]
I'm not entirely sure as to why but I've used this program endlessly (love it to death) and randomly today when I got on, my profile was corrupted. No biggy, the program made me backups so I went, got the backup, presto! Working as good as new! But now, my world isn't being analyzed. When trying to analyze my character, it shows nothing under Campaign and that my Adventure mode is grayed out and can't be clicked. Any help here would be great! Thanks!
![image](https://user-images.githubusercontent.com/49470272/82953180-4e7e1880-9f78-11ea-8fa9-614bc7494625.png)

**Comment by Razzmatazzz** [comment]
Can you upload your profile.sav and the corresponding save_X.sav file for that character somewhere and send me the link? My guess is that the backup you restored had a good profile.sav file but a bad save_X.sav file.

**Comment by Razzmatazzz** [comment]
Also, does the log tab of the main window show any errors?

**Comment by Toonsie** [comment]
Log tab showed absolutely no errors whatsoever. Link will be the save and profile. Thank you for the quick response as well! https://gofile.io/d/O5xPPw

**Comment by Toonsie** [comment]
I think I found myself a solution! I realized on your program, you can right click your backups and analyze the worlds still. Going through them, I realized I had a backup that was still at the same progress (Cultist (290)) and when I analyzed it, it showed the Campaign and Adventure still working! So I turned off Steam Cloud, deleted everything in the save folder and launched the game. Made a new character, got off, deleted once more and put that backup in and now, can analyze just fine like before! So far, no issues but hopefully regardless you're able to figure out any issue with that sav. Thank you once more!

**Comment by Razzmatazzz** [comment]
Ok, good to hear you got it working. The save file you sent me *should* have processed fine in the analyzer, but it does sound like Steam Cloud was interjecting the corrupted save file. I can't really control what Steam is doing, so I'm going to mark this closed.
