### ISSUE TITLE
Ravager's Haunt

### ISSUE THREAD

**Issue by MinionXV** [Razzmatazzz/RemnantSaveManager#16]
Hello,

There's a typo in the line 94 of the "RemnantWorldEvent.cs" file.
"TheRavagersHaunt" should be replaced with "TheRavager'sHaunt".
This cause some items and simulacrum to be chown in Ravager's Haunt instead of The Scalding Glade.

**Comment by Razzmatazzz** [comment]
Will be fixed in the next version. Thanks for reporting. I must have added the apostrophe in GameInfo.xml at some point and then forgot to change that line.
