### ISSUE TITLE
Add support to linux

### ISSUE THREAD

**Issue by SandHilt** [Razzmatazzz/RemnantSaveManager#19]
Hello, could a .deb version.

**Comment by Razzmatazzz** [comment]
My understanding is that Remnant is Windows-only on PC, so a Linux version wouldn't be much use. Even if I'm incorrect, the entire project is written in C#, so I'm not too inclined to port it over to something that would run on Linux.

**Comment by infirit** [comment]
> My understanding is that Remnant is Windows-only on PC, so a Linux version wouldn't be much use.

Yes but steam supports running windows games on gnu+linux through wine at good framerates.

> Even if I'm incorrect, the entire project is written in C#, so I'm not too inclined to port it over to something that would run on Linux.

There is mono which implements dotnet/C# on windows, macos and linux. There are several cross platform applications using dotnet/c#.

I don't care for a port as I do my gaming on windows but you should at least be aware that gaming and dotnet/c# on linux is a thing 😄

**Comment by Razzmatazzz** [comment]
Spending any time on a Linux port would be time better spent on something else for me. The source code is available for anyone who wants to fork and do a port.
