### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by xingped** [Razzmatazzz/RemnantSaveManager#2]
I'm not sure why, but the save manager keeps crashing. Nothing in the log file. On the latest version.

**Comment by Razzmatazzz** [comment]
Maybe the game was updated recently and I need to update the save manager. Are you doing anything in particular when it crashes, or does it just crash immediately when you launch it?

**Comment by xingped** [comment]
It doesn't crash immediately or when I'm doing anything in particular, just seemingly at random. I'm not sure if it crashes when it tries to save or not because there's no new backup save when I relaunch.

**Comment by Razzmatazzz** [comment]
Ok, I'll look into it. Thanks for reporting!

**Comment by Razzmatazzz** [comment]
I haven't been able to reproduce a crash yet. Does it make any save backups, or does that seem to be what's crashing it? If it's not making any backups, does it crash if you push the "Backup" button to manually backup your current save?

**Comment by xingped** [comment]
Does not crash after manually pressing backup, so saving does not seem to be the issue. Only that it crashes after running for a few minutes. Is there any way I can capture a stack trace or crash log for you?

**Comment by Razzmatazzz** [comment]
In the same folder as RemnantSaveManager.exe, is there a log.txt file?

**Comment by xingped** [comment]
Yep, first thing I checked and there was nothing useful in it. Can share when I get home later though.

**Comment by xingped** [comment]
log.txt:
```
1/14/2020 8:19:59 PM: Loading...
1/14/2020 8:19:59 PM: Loading...
1/14/2020 8:19:59 PM: Current save date: 1/14/2020 8:18:01 PM
1/14/2020 8:19:59 PM: Backups found: 2
1/14/2020 8:19:59 PM: Last backup save date: 1/14/2020 8:17:01 PM
1/14/2020 8:19:59 PM: No new game info found.
```
