### ISSUE TITLE
False Positive Item Drops

### ISSUE THREAD

**Issue by WhipJr** [Razzmatazzz/RemnantSaveManager#22]
The Abrasive Amulet in the image below exists, however the Devouring Loop does not in this location. i have scoured the area for well over half an hour now just to be sure. 

![image](https://user-images.githubusercontent.com/6914965/90580105-14e33500-e196-11ea-8ec4-e289101bfe62.png)

**Comment by Razzmatazzz** [comment]
I can't imagine what could cause a false positive.

**Comment by WhipJr** [comment]
the recent updates? i have no clue. should i post the backup?

**Comment by WhipJr** [comment]
Alright i finally found it. the Devouring loop is located in the location past the dungeon on the opposite side of the Iskal Queen locked gate; so in the main overworld area, not in The Capillary dungeon.

**Comment by Razzmatazzz** [comment]
Yes, the locations are best estimates. Not possible to be more exact, unfortunately.

**Comment by WhipJr** [comment]
well that explains it. thank you!
