### ISSUE TITLE
Program crashes when changing save folder

### ISSUE THREAD

**Issue by Bryggz** [Razzmatazzz/RemnantSaveManager#28]
Hey hey,
Great program, first off! Very grateful to have it. I've encountered a new issue with this release, though. I save all of my backup folders to a OneDrive folder to give myself some pseudo-cloudsaving capabilities. Every time I change the backup directory to the OneDrive folder though, the program crashes. This is 100% repeatable.

**Comment by Razzmatazzz** [comment]
I changed my backups folder to OneDrive, told it move my backups there, and it didn't crash. Not sure what's going on here.

**Comment by Bryggz** [comment]
Okay, thank you for checking. I'll see if there's any additional useful information that can help identify this.
