### ISSUE TITLE
Crash on Warp

### ISSUE THREAD

**Issue by monkeytaco** [Razzmatazzz/RemnantSaveManager#3]
Using current build of Remnant as of today and version 1.95.4 as well as 1.95.3 of the save manager.
Steps to reproduce:
Launch Game
Open Save Analyzer
Traveled to or from an Adventure in Earth.
Save manager crashes mid-travel.
Log data:
2/23/2020 05:20:42: Loading...
2/23/2020 05:20:42: Loading...
2/23/2020 05:20:42: Current save date: 2/23/2020 05:19:16
2/23/2020 05:20:42: Backups found: 5
2/23/2020 05:20:42: Last backup save date: 2/23/2020 05:19:06
2/23/2020 05:20:43: No new game info found.
2/23/2020 05:20:44: Backup completed (2/23/2020 05:19:16)!
2/23/2020 05:20:44: Showing current save world analyzer...

**Comment by Razzmatazzz** [comment]
Thanks for reporting. I can't get it to crash. How many characters do you have? Which ones are hardcore characters? Are any characters in the tutorial (pre-class selection) part of the game?

**Comment by monkeytaco** [comment]
Two characters, was three but deleted one. Save 0 is default, save 2 is hardcore. No characters currently in the tutorial.

**Comment by monkeytaco** [comment]
[637185049466726489.zip](https://github.com/Razzmatazzz/RemnantSaveManager/files/4269737/637185049466726489.zip)
Current backup attached.

**Comment by monkeytaco** [comment]
Solution found. When it's run as admin, the problem doesn't persist.

**Comment by Razzmatazzz** [comment]
That's strange, because I think I see what was causing the issue. Had to do with deleting the character.

**Comment by Razzmatazzz** [comment]
Actually, no, the skipping from save_0 to save_2 doesn't cause the problems I thought it might. I guess it's good that running as admin fixes it, but I'm not sure why that is.

**Comment by monkeytaco** [comment]
Best guess? Something related to unloading/loading. Maybe the game does something to the save file that causes it? It's on my boot drive, which is an M.2 SSD, not that I think that is necessarily the cause, just more info.

**Comment by GeorgePratt** [comment]
I have the game on my boot drive which is an M2 and the Save Manager on another volume. I do not get this behaviour. Since running in admin works, I'm guessing it's actually more likely that one of the system folders that the Save Manager requires to use, either to access the game files, or to save the backups, is actually locked out for your user and you would need to manually go into them and transfer folder ownership. That might solve the issue.
