### ISSUE TITLE
Missing Items: Survival Trinkets

### ISSUE THREAD

**Issue by Snowfunk** [Razzmatazzz/RemnantSaveManager#30]
Black Cat Band
Bright Steel Ring
Ring Of Flawless Beauty
White Rose

Are all listed under Survival, Missing items. 
These however, are not account bound, and thus not "unlockable". 
They are simply trinkets exclusive, to obtain and use within the survival game mode.
So I would suggest not having them noted, under missing items at all.

**Comment by Razzmatazzz** [comment]
Can you point me to a source for this? From my understanding, anything "unlocked" in survival becomes available for you to use in the rest of the game.

**Comment by Snowfunk** [comment]
The Ring Of Flawless Beauty seems to be working, somewhat properly.
The other 3, I was at a loss. I have been grinding survival runs, and have managed several 50+ boss runs which should have unlocked them. 
I also asked around the Discord, and they seem to unlock at incredible unpredictable times, if at all.
However, submitting a bug report, I got a reply saying that they are bugged, and won't unlock on an old character, but will if you make a new one. Anyways, as it seems, they should be unlockable. Just the process being buggy atm. So it seems this is nothing you should concern yourself with. Ty for all your work.
