### ISSUE TITLE
Windows 10 Reports Trojan Threat in version 1.95.36

### ISSUE THREAD

**Issue by lutrinae** [Razzmatazzz/RemnantSaveManager#31]
After first attempted to download and run the newest version 1.95.37 (which downloaded an empty zip folder instead), I tried version 1.95.36 but Windows detected the Trojan Win32/Emali.A!cl. Are you aware of this? 

I also downloaded Version 1.95.35, which runs with no issues.

**Comment by Razzmatazzz** [comment]
I am aware of Windows Defender showing false positives. Not much I can do about that, unfortunately.

**Comment by lutrinae** [comment]
Hmm, OK, I'll add an exception then. Tho what of 1.95.37 downloading an empty folder? I've tried multiple times now (the older versions work just fine). Thanks!

**Comment by Razzmatazzz** [comment]
I just downloaded it, and it's not an empty folder for me.

**Comment by lutrinae** [comment]
I tried again in Chrome and it downloaded just fine. Must be some Firefox quirk. Go figure. 

Anyway, thanks for making this awesome tool! Saved me tons of time!
