### ISSUE TITLE
语言

### ISSUE THREAD

**Issue by yangpengfei194** [Razzmatazzz/RemnantSaveManager#35]
全是英文的看不懂翻译有点麻烦 有没有汉化的

**Comment by Razzmatazzz** [comment]
> 
> 
> It’s all in English. It’s a bit troublesome to not understand the translation.

Yes. Unfortunately, I can only speak a couple words of Chinese and can't read/write any. [Someone else has already raised the issue and started their own Chinese translation](https://github.com/Razzmatazzz/RemnantSaveManager/issues/27).
