### ISSUE TITLE
Can you please make it so that it stops asking me to update to the latest version every single time? I'm using 1.95.36 because 1.95.37 doesn't work.

### ISSUE THREAD

**Issue by RemnantUser0** [Razzmatazzz/RemnantSaveManager#36]

**Comment by Razzmatazzz** [comment]
In what way does the latest version not work? To disable the new version notification, I'd have to release a new version... and if the current version doesn't work for you, that new version probably wouldn't either.

**Comment by RemnantUser0** [comment]
It was working fine until one day I deleted the files in my SaveGames including save_0.sav, to copy-paste the contents of a different backup in there. I'm not sure what happened or if it was because of that or something else entirely, but it made 1.95.37 not open when i click on it. 

The 1.95.38 is working fine, but I just got the Subject 2923 DLC. I'm playing the Subject 2923 as my campaign, but for some reason it shows main game areas and no Subject 2923 areas. My Adventure tab is faded out, making it so that I cannot click on it and view any Adventure areas at all.

**Comment by Razzmatazzz** [comment]
How many characters do you have? Is it possible the analyzer is showing the information for a different character?

**Comment by RemnantUser0** [comment]
Ah yes. I got it now. I only have one character in the game, but for some reason I also have other files like save_0.sav, save_1.sav and save_3.sav. So I deleted them one by one until the world analyzer will show the world of the correct save file. Turns out my character is on save_3.sav
