### ISSUE TITLE
Talisman of Perseverance is listed in 'Normal' and 'Survival'. Should be 'Survival' only.

### ISSUE THREAD

**Issue by AlphaRage** [Razzmatazzz/RemnantSaveManager#37]
Line 512 in XML

**Comment by Razzmatazzz** [comment]
According to the devs, it can spawn in Yaesha as well: https://www.reddit.com/r/remnantgame/comments/gecq6g/i_unlocked_the_talisman_of_perseverance_in_the/fpmpoea/?context=1000

**Comment by AlphaRage** [comment]
Interesting. That information is not on the wiki and I have every other item except for this one now, meaning I did a ton of Yaesha runs/rolls and it never appeared. Not suggesting the dev comment isn't true anymore but I'm skeptical because we had big patches and a new DLC. I guess only rolling a few hundred times or asking the devs again would confirm it for sure but that's not on me, sorry!

**Comment by Razzmatazzz** [comment]
Yeah it's a weird situation. If I don't include it as a separate event and someone rolls it on Yaesha, then it won't show as a missing item in that context. But, like you say, it's possible that it's no longer a random event on Yaesha. Unfortunately, it's basically impossible to disprove that something spawns somewhere. Unless the devs clarify, I'll just have to keep fielding the inquiries from folks pointing out that seemingly shouldn't appear outside survival.

**Comment by AlphaRage** [comment]
Well, then there's nothing to see here. I guess you could make a note and that's it. Thanks for the clarification.
