### ISSUE TITLE
World Analyzer says an item drop is available, but can't find it

### ISSUE THREAD

**Issue by Rsmqi** [Razzmatazzz/RemnantSaveManager#42]
Hello, as the title says, I can't seem to find an item that the world Analyzer says is there. This is in earth - sorrow's field with the item pillar of stone. 1st playthrough on normal.

**Comment by Razzmatazzz** [comment]
[Item locations are "best estimates."](https://github.com/Razzmatazzz/RemnantSaveManager/wiki) When an item shows as being in a dungeon, there's a chance that item is actually in the overworld that led to the dungeon. This is more likely to be the case where multiple items are shown to be in a dungeon.
