### ISSUE TITLE
Is there a way to disable hardware acceleration?

### ISSUE THREAD

**Issue by Suddow** [Razzmatazzz/RemnantSaveManager#43]
As per the title, looking to disable hardware acceleration.

**Comment by Razzmatazzz** [comment]
I'm not sure I understand. Are you asking about disabling hardware acceleration in the Save Manager app? I'm not sure if the app even uses hardware acceleration. If it does, I'm not sure if that's possible to disable it. Are you experiencing some kind of issue and you've determined hardware acceleration is to blame?

**Comment by Suddow** [comment]
Yes, it causes gsync to behave oddly whenever the program is the focus (and may be responsible for stuttering of my game too, though it happens so infrequently that I'm not sure what the actual cause is yet).  In the past I had noticed issues with apps that were hardware accelerated while I was also playing a game, so it's usually the first thing I try to disable.

**Comment by Razzmatazzz** [comment]
I haven't experienced any issues with G-sync or game stuttering. The program doesn't use any hardware acceleration beyond what's inherent in a WPF app. And it doesn't register as an app to record with shadow play as some other apps do.
