### ISSUE TITLE
Looking for Remnant Windows 10 Version Save File Location

### ISSUE THREAD

**Issue by chrstnrlv** [Razzmatazzz/RemnantSaveManager#47]
![RemnantW10file](https://user-images.githubusercontent.com/84753899/119427240-b45ec680-bcd8-11eb-83d8-e2dbcb90b38d.png)
![RemnantW10file2](https://user-images.githubusercontent.com/84753899/119427244-b6288a00-bcd8-11eb-9299-dec3caf8cc75.png)
![RemnantW10file3](https://user-images.githubusercontent.com/84753899/119427257-b9bc1100-bcd8-11eb-9748-1c9586cfac7c.png)
![RemnantW10file4](https://user-images.githubusercontent.com/84753899/119427261-bb85d480-bcd8-11eb-89ca-cc83a0fd2347.png)
Just curious if I can actually find my save files. I can't make a copy/compress my Remnant Folder into a zip file because I don't have the permission to, all I can do is take screenshots. I'm a newbie in this kind of stuff.

**Comment by Razzmatazzz** [comment]
You're looking in the game installation folder, not the save location. Read #46 which describes where to look for your save files.

**Comment by chrstnrlv** [comment]
Thank you so much, I've been looking at the wrong ones after all. This helps
