### ISSUE TITLE
1.95.12 Crash on Moving Backups

### ISSUE THREAD

**Issue by GeorgePratt** [Razzmatazzz/RemnantSaveManager#5]
As title, wanted to move my save backups folder, keeps crashing when I click move.

**Comment by Razzmatazzz** [comment]
Having trouble replicating this. Does anything get moved to the new folder you've selected, or is it still empty?

**Comment by GeorgePratt** [comment]
Does not get moved. I am not replicating the folder structure seen in AppData (so no Saved/Backups). I'm also saving to a drive other than the C drive.

**Comment by Razzmatazzz** [comment]
Moving the backups to another volume was the issue. Fixed in latest version. Thanks for reporting!
