### ISSUE TITLE
BUG: Adventure Mode Analyzer

### ISSUE THREAD

**Issue by DannyHeads** [Razzmatazzz/RemnantSaveManager#50]
Recently Downloaded the save game manager(9/26/21) and cannot seem to get the Analyzer to work for adventure mode. I've used the red crystal and still the tab remains grayed out. I'm using the current steam version and own all of the DLC. The adventure mode world is Corsus. 

Tried adventure mode on earth and still the tab is greyed out.

*edit - Added which adventure I was running

**Comment by Razzmatazzz** [comment]
Did you travel to your world after rolling?

**Comment by DannyHeads** [comment]
Yes I travelled to the world

**Comment by Razzmatazzz** [comment]
Strange; I'm not sure what could have been causing it to not pick up your adventure roll. At least it's working now!

**Comment by DannyHeads** [comment]
To anyone else: 
I solved the issue by making a new character
-starting an adventure on them
-traveled to world
-deleted new character 
-loaded up old save and everything works now
