### ISSUE TITLE
Remnant 2 support?

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [Razzmatazzz/RemnantSaveManager#62]
Any plan to provide a similar tool for Remnant 2 dropping next week?

**Comment by Razzmatazzz** [comment]
The save files of Remnant 2 are obfuscated, so I don't know whether it will be feasible.

Remnant 1's save files could be opened in Notepad and you could read all the gear your character already has and all the events that rolled in your world in plaintext. When you open Remnant 2's save files in Notepad, there's no plaintext. Only inscrutable characters that I don't currently know how to decipher.

**Comment by KittySkin** [comment]
Provided the deobfuscation code, are you willing to add remnant 2 support?
Not a hard promise, but I can start digging and ping some other reverse engineers to give me a hand getting it.

**Comment by Razzmatazzz** [comment]
I'd like to create a new app for Remnant 2, but the feasibility of that also depends on what the de-obfuscated save files actually look like. It's possible they're much more complex than the saves for the first game.

**Comment by crackedmind** [comment]
@Razzmatazzz Saves aren't obfuscated. It simply deflated. But splited in chunks. 

Chunk header starts by: C1 83 2A 9E 22 22 22 22 
Chunk header size: 49 bytes

![image](https://github.com/Razzmatazzz/RemnantSaveManager/assets/1381503/644d8348-84cd-4411-8bd7-9571330210eb)

You can use this
http://aluigi.altervista.org/mytoolz/offzip.zip

```
mkdir save_0
offzip.exe -a save_0.sav save_0
```

and you get all uncompressed chunks

**Comment by crackedmind** [comment]
Created simple tool to unpack saves (required .Net 6/7)
https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0

**Comment by Razzmatazzz** [comment]
Thanks for the explanation and code! I'm working on an app for Remnamt 2.

**Comment by DEVxALMIGHTY** [comment]
Thank you! The tool for R1 was incredibly useful and we need one even more for R2.

**Comment by mastergaming234** [comment]
> Created simple tool to unpack saves (required .Net 6/7) https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0

question could I use this upacker to edit my character appearance like you could do with remnant 1? if yes how would  I go about repackaging the save file so that the game reads it?

**Comment by Razzmatazzz** [comment]
Got something working but probably with a lot of bugs:
https://github.com/Razzmatazzz/RemnantSaveGuardian

Note that "missing items" won't really work until all the items for events have been added to events. I haven't had time to play past the tutorial, so that work isn't close to done.

**Comment by CrimtS** [comment]
Hey @Razzmatazzz , I could launch any version you uploaded. Are you sure they launch correctly at the moment?

**Comment by Razzmatazzz** [comment]
Probably best to open an issue in that repo. Do you have the .net framework installed?

**Comment by CrimtS** [comment]
Have just installed a fresh version, still doesn't seem to work. I will try some workarounds from my side

> Do you have the .net framework installed?

**Comment by DGarHen** [comment]
> Have just installed a fresh version, still doesn't seem to work. I will try some workarounds from my side
> 
> > Do you have the .net framework installed?

maybe is the "there is not any project to execute" error? or something like that?... you could use the --project to target the csproj file

**Comment by davidcwilkerson** [comment]
> Got something working but probably with a lot of bugs: https://github.com/Razzmatazzz/RemnantSaveGuardian
> 
> Note that "missing items" won't really work until all the items for events have been added to events. I haven't had time to play past the tutorial, so that work isn't close to done.

Thanks so much for your work.  Big fan   However, I don't think the analyzer is working on adventure mode.  It doesn't seem to change the items or locations when I re-roll.  Any idea what I could be doing wrong?

**Comment by Razzmatazzz** [comment]
Yep, that's a known issue and being worked on: https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/6

**Comment by crackedmind** [comment]
> > Created simple tool to unpack saves (required .Net 6/7) https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0
> 
> question could I use this upacker to edit my character appearance like you could do with remnant 1? if yes how would I go about repackaging the save file so that the game reads it?

Nope. You can't do this.

**Comment by Crimir85** [comment]
when i try to open it, the app closes like 1 second later...

**Comment by DreadOp** [comment]
I would love you so hard if you can get this to work with Xbox file manager eventually (if you manage to figure it out on PC). I have to play on Xbox with my casual IRL buddies. :bigsad:

**Comment by Razzmatazzz** [comment]
Idk if it's even possible to do on Xbox. I suspect not.

**Comment by SgtPitbull** [comment]
Sorry for be new to this.
But how do i run this ?

As i am that point i want to farm for item i still need, This be a great thing to use.

Love it for the Remnant

Thanks kindly.

**Comment by Razzmatazzz** [comment]
@SgtPitbull Go to the RemnantSaveGuardian repository (https://github.com/Razzmatazzz/RemnantSaveGuardian) and download the latest release.

**Comment by mastergaming234** [comment]
> > > Created simple tool to unpack saves (required .Net 6/7) https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0
> > 
> > 
> > question could I use this upacker to edit my character appearance like you could do with remnant 1? if yes how would I go about repackaging the save file so that the game reads it?
> 
> Nope. You can't do this.

What would need to do in order to make the character data read able if I wanted to change my character face,voice and hair style.

**Comment by crackedmind** [comment]
> > > > Created simple tool to unpack saves (required .Net 6/7) https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0
> > > 
> > > 
> > > question could I use this upacker to edit my character appearance like you could do with remnant 1? if yes how would I go about repackaging the save file so that the game reads it?
> > 
> > 
> > Nope. You can't do this.
> 
> What would need to do in order to make the character data read able if I wanted to change my character face,voice and hair style.

We can't do it right now and in the future.

**Comment by SgtPitbull** [comment]
> @SgtPitbull Go to the RemnantSaveGuardian repository (https://github.com/Razzmatazzz/RemnantSaveGuardian) and download the latest release.

I have done that.

I follow the steeps, BUT 

I dont have 4. Run RemnantSaveGuardian.exe
I have RemnantSaveGuardian.sin, i have RemnantSaveGuardian.csproj

So i am sure there is something i need to do ?

Sorry for being a total newbies on this...

Kindly.

**Comment by AndrewSav** [comment]
You need to download `RemnantSaveGuardian.zip`

**Comment by Razzmatazzz** [comment]
Closing this per #63
