### ISSUE TITLE
Won't Back Up my Saves

### ISSUE THREAD

**Issue by sqorpeus** [Razzmatazzz/RemnantSaveManager#7]
It constantly says Deleteing excess backup but never does.  Pressing the Backup button does nothing, nor does restarting the program.  This issue started with the latest release yesterday.  As an aside, would it be possible to add a zoom feature to the World Analyzer?
![razzmatazzworldanalyzerwontbackupsavefiles](https://user-images.githubusercontent.com/64917540/81202984-59efac80-8f95-11ea-8274-823be2dc406a.png)

**Comment by Razzmatazzz** [comment]
What are your settings for backup interval and number of backups to keep?

Not sure how easy it would be to add a zoom feature, but I'll look into it. Is it the missing item text that's too small specifically, or everything in general? Looks like you've done some significant reskinning of Windows; I'm not really sure how to account for that.

**Comment by sqorpeus** [comment]
I have the interval set for 2 minutes and the number of backups to keep
unlimited.  As for the zoom, exactly the opposite.  Everything is too
large.  I resize the columns to fit everything and a couple minutes later
they revert to the old settings.  Most of the reskinning is just to turn
everything to dark mode.

**Comment by Razzmatazzz** [comment]
Looks like there was a bug where it wasn't honoring the "0 = unlimited" text from the settings window. Will be easy to fix. In the meantime, just set the limit to something like 100 and it should work.

I'll see about adding resizing options to the analzyer or maybe having it remember column widths.

**Comment by sqorpeus** [comment]
It seems to be working now.  Thank you much for your help and
considerations.

**Comment by sqorpeus** [comment]
It's giving me that message again.  Could every 2 minutes be overdoing it?

**Comment by Razzmatazzz** [comment]
How many save backups do you have? If you've reached 100, then it'll be deleting the older backups.

**Comment by sqorpeus** [comment]
I have about 40 backups.  I turned automatic backup off to see if I could
revert to manual as I was doing before and now clicking the Backup button
does nothing.

**Comment by Razzmatazzz** [comment]
If you click the "open backup folder" button, how many folders are in there?

**Comment by sqorpeus** [comment]
117

**Comment by Razzmatazzz** [comment]
Do any of those folders have names other than the numbered ones the backups have?

**Comment by sqorpeus** [comment]
Nope.

**Comment by Razzmatazzz** [comment]
Are you using the default backup folder or did you specify a new one? You could try deleting all those backup folder or moving them somewhere else and then seeing if the program functions normally. I'm at the limit for my backups and I'm not having an issues with it deleting the oldest backups to make new backups. Without being able to replicate this, that makes it hard to troubleshoot.

**Comment by sqorpeus** [comment]
I'm using the default backup folder location.  I just deleted all the
folders and restarted your program.  It seems to be working now.

**Comment by Razzmatazzz** [comment]
New version should now allow unlimited backups if you set the max to 0. Wouldn't really recommend that, though, as you'll be eating up a lot of hard drive space unnecessarily.
