### ISSUE TITLE
Deleting an already deleted backup closes the program

### ISSUE THREAD

**Issue by Djoums** [Razzmatazzz/RemnantSaveManager#8]
Minor issue : if you delete a backup folder manually then delete that same backup from RemnantSaveManager, the program hangs a bit then closes itself.

**Comment by Razzmatazzz** [comment]
Program is crashing because it tries to delete a folder that doesn't exist. Next version will fix the problem. In the meantime, don't do what's making it crash. :) Thanks for reporting!
