### ISSUE TITLE
The delete key does not delete anything

### ISSUE THREAD

**Issue by Djoums** [Razzmatazzz/RemnantSaveManager#9]
Minor issue : the delete key removes a backup from the list but does not actually do anything, only the right-click/delete menu works.

**Comment by Razzmatazzz** [comment]
Interesting. I would not have expected the delete key to have native functionality for the DataGrid control, but apparently it does. Should be able to fix it. In the meantime, just use the right-click menu. Thanks for reporting.

**Comment by Djoums** [comment]
An idea on that subject : it would be nice to be able to multi-select backups for removal (ctrl-click and shift-click). When you backup every 10min you endup with a lot of them.

**Comment by Razzmatazzz** [comment]
Just set the maximum number of backups to keep to a lower number and let the program handle deleting them for you.
